[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "keelcrab"
version = "0.1.0"
description = "Hull robot sim and controller"
authors = [{ name = "Marcus Collard" }]
dependencies = []

[tool.setuptools.packages.find]
where = ["."]
